//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yt_dlp_Interface {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Presets : global::System.Configuration.ApplicationSettingsBase {
        
        private static Presets defaultInstance = ((Presets)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Presets())));
        
        public static Presets Default {
            get {
                return defaultInstance;
            }
        }
    }
}
